services:
  redis:
    container_name: engine-redis
    image: redis:7-alpine
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    container_name: engine-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game-engine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/bin/pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 120