"""empty message

Revision ID: 55022008cf73
Revises: 3c0bbf6d8765
Create Date: 2023-06-29 16:14:53.710573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55022008cf73'
down_revision = '3c0bbf6d8765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_pid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_id')
        batch_op.drop_column('engine_pid')

    # ### end Alembic commands ###
