"""empty message

Revision ID: 84dbc5817925
Revises: b5aefbcac0e0
Create Date: 2025-01-27 13:04:51.470537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84dbc5817925'
down_revision = 'b5aefbcac0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_lobby',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('lobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_teams', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_teams', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('min_team_players', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_team_players', sa.Integer(), nullable=False))
        batch_op.drop_column('team_roles')
        batch_op.drop_column('team_number')
        batch_op.drop_column('team_size')

    with op.batch_alter_table('lobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_started', sa.Boolean(), server_default='false', nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lobby_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lobby', ['lobby_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lobby_id')

    with op.batch_alter_table('lobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('is_started')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_size', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('team_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('team_roles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('max_team_players')
        batch_op.drop_column('min_team_players')
        batch_op.drop_column('max_teams')
        batch_op.drop_column('min_teams')

    op.drop_table('team_lobby')
    # ### end Alembic commands ###
