"""empty message

Revision ID: 945459f6b707
Revises: 55022008cf73
Create Date: 2023-06-29 16:39:12.204756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945459f6b707'
down_revision = '55022008cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_session', schema=None) as batch_op:
        batch_op.drop_constraint('team_session_team_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_session_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_session_session_id_fkey', 'session', ['session_id'], ['id'])
        batch_op.create_foreign_key('team_session_team_id_fkey', 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###
