"""empty message

Revision ID: b5aefbcac0e0
Revises: ec325180dd7f
Create Date: 2024-01-10 12:40:15.973862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5aefbcac0e0'
down_revision = 'ec325180dd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('session_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['winner_id'], ['id'])
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('session_team_id_fkey', 'team', ['team_id'], ['id'])
        batch_op.drop_column('winner_id')

    # ### end Alembic commands ###
